In [1]:
import numpy as np

In [3]:
a = np.array([3, 4, 5])
b = np.array([1, 3, 6])

A **dot product** is defined as follows:

$$\vec{a}\cdot\vec{b} = ||\vec{a}|| \space ||\vec{b}|| \cos(\theta)$$

Broken down, we are combining the magnitudes of vectors $\vec{a}$ and $\vec{b}$ on the basis of the angle between them. 

* When $\theta = 0$ (the vectors point in the exact same direction), the dot product is greatest, because $\cos(\theta) = 1$.
* When $\theta = \pi/2$ (the vectors are perpendicular), the dot product equals zero, because $\cos(\pi/2) = 0$.
* When $\pi/2 < \theta < 3\pi/2$ (the vectors are pointing in opposed directions), the dot product is negative.

It turns out that computing the dot product is quite easy, and need not involve any trigonometry:
$$\vec{a} = (a_1, a_2, a_3)$$

$$\vec{b} = (b_1, b_2, b_3)$$

$$\vec{a}\cdot\vec{b} = a_1b_1 + a_2b_2 + c_3b_3$$

I do not know why the geometric and algebraic definitions are equivalent, and I hope to understand at some point in my life.

In [4]:
np.dot(a,b)

45

A **cross product** is defined as follows:

$$\vec{a} \times \vec{b} = ||\vec{a}|| \space ||\vec{b}|| \sin(\theta) \space \vec{u} $$

where $\vec{u}$ is a unit vector perpendicular to the plane containing $\vec{a}$ and $\vec{b}$ such that $(\vec{a}, \vec{b}, \vec{u})$ is positively oriented. That is, we want the cross product to be in the orientation of the thumb when we make this silly looking gesture with our right hand:

![The right hand rule for the cross produtc](righthandrule.svg)

The cross product has two special properties:

1. The cross product is perpendicular to both $\vec{a}$ and $\vec{b}$. This is why the cross product only works in three dimensions.
2. The cross product measures how far apart $\vec{a}$ and $\vec{b}$ are measuring.

The cross product can be calculated algebraically, but it really sucks.

$$\vec{a} = (a_1, a_2, a_3)$$

$$\vec{b} = (b_1, b_2, b_3)$$

$$\vec{a} \times \vec{b} = \begin{bmatrix}
a_2b_3 - a_3b_2\\
a_3b_1 - a_1b_3\\
a_1b_2 - a_2b_1
\end{bmatrix}$$

In [5]:
np.cross(a,b)

array([  9, -13,   5])

Because the cross product is perpendicular to both $\vec{a}$ and $\vec{b}$, taking the dot product of either $\vec{a}$ or $\vec{b}$ with $\vec{a}\times\vec{b}$ will yield 0.

In sum:

1. The dot product returns a number, but the cross product returns a vector.
2. The dot product works in any number of dimensions, but the cross product only works in three dimensions.
3. The dot product measures how much two vectors point in the same dimension, but the cross product measures how much two vectors point in different directions.

In Python, we can create matrices quite easily:

In [10]:
x = np.matrix([[1,2,3],[4,5,6]])
x

matrix([[1, 2, 3],
        [4, 5, 6]])

We can check the dimensions like so:

In [11]:
x.shape

(2, 3)

To **multiply** two matrices, the number of columns of the first matrix must equal the number of rows in the second matrix. We multiply such that the first element in the column of the first matrix multiplies with the first element in the row of the second matrix and so on, and then we sum it all.

$$
\begin{bmatrix}
0 & 1 \\
2 & 3
\end{bmatrix}
\begin{bmatrix}
4 & 5 \\
6 & 7
\end{bmatrix}
=
\begin{bmatrix}
0 \cdot 4 + 1 \cdot 6 & 0 \cdot 5 + 1 \cdot 7 \\
2 \cdot 4 + 3 \cdot 6 & 2 \cdot 5 + 3 \cdot 7
\end{bmatrix}
=
\begin{bmatrix}
6 & 7 \\
26 & 31
\end{bmatrix}
$$

The dimensions of the product matrix will always be the number of rows in A and the number of columns in B. A $1 \times 2$ matrix and a $2 \times 1$ matrix will produce a $1 \times 1$ matrix:

$$
\begin{bmatrix}
0 & 1
\end{bmatrix}
\begin{bmatrix}
2 \\
3
\end{bmatrix}
=
\begin{bmatrix}
0 \cdot 2 + 1 \cdot 3
\end{bmatrix}
=
\begin{bmatrix}
3
\end{bmatrix}
$$

In [14]:
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
b = np.matrix([[11,12,13],[14,15,16],[17,18,19]])
c = np.matrix([[21],[22],[23]])

In [15]:
a*c

matrix([[134],
        [332],
        [530]])

A **transpose** of a matrix switches the rows and the column, such that each entry $a_{i,j}$ becomes $a_{j,i}$. For example, given:

$$
A = \begin{bmatrix}
3 & -2 & 5\\
4 & 2 & 1
\end{bmatrix}
$$

The transpose is:

$$
A^T = \begin{bmatrix}
3 & 4 \\
-2 & 2\\
5 & 1
\end{bmatrix}
$$

In [16]:
np.transpose(c)

matrix([[21, 22, 23]])

A **determinant** represents how much a matrix stretches or squeezes space. Given unit vectors in two dimensions, the area of the square demarcated by the unit vectors is 1. 

* If the determinant is greater than 1, the matrix stretches the space.
* If the determinant equals 1, the matrix does not stretch or squeeze the space. An example would be rotation.
* If the determinant is less than 1, the matrix squeezes the space.
* If the determinant is equal to 0, the matrix squeezes the space such that the unit vectors now lie on the same line.
* If the determinant is less than 0, the matrix flips orientations.

For a **two-dimensional matrix**, the formula for the determinant is:

$$\det(\begin{bmatrix}
a & b \\
c & d\end{bmatrix}) = ad-bc$$.

For example:

$$\det(\begin{bmatrix}
1 & 3\\
5 & 4
\end{bmatrix}) = 1 \cdot 4 - 3 \cdot 5 = -11$$

So this matrix flips the orientations of the space.

For a **three-dimensional matrix**, it is a much greater PITA.

$$\det(\begin{bmatrix}
a & b & c\\
d & e & f\\
g & h & i
\end{bmatrix}) = a \space \det(\begin{bmatrix}e & f \\ h & i\end{bmatrix}) - b \space \det(\begin{bmatrix}d & f \\ g & i\end{bmatrix}) + c \space \det(\begin{bmatrix}d & e \\ g & h\end{bmatrix}) $$.

The **cross product** of two vectors $\vec{a}$ and $\vec{b}$ is actually the determinant of the three-dimensional vector:

$$\det(\begin{bmatrix}
\vec{i} & \vec{j} & \vec{k}\\
a_1 & a_2 & a_3\\
b_1 & b_2 & b_3
\end{bmatrix})$$

Where the first row consists of the unit vectors.

The **linear combination** of vectors is the sum of vectors, each scaled by a constant factor. For example,
$$12\vec{a} + -2\vec{b}$$
is a linear combination. It is the case that a linear combination of:
* two non-collinear vectors of magnitude greater than zero has a **span** that covers the space of real numbers in two dimensions.
* two collinear vectors has a span that only covers a line.
* a vector of magnitude zero has a span that only covers the point (0,0).

A vector in a set of vectors is **linearly independent** if the vector cannot be reduced to any linear combination of the other vectors in the set. That is, the vector adds a new dimension that the set of vectors can access. For example, if:

$$\vec{a} = \begin{bmatrix}
1\\
3
\end{bmatrix}$$

and 

$$\vec{b} = \begin{bmatrix}
2\\
6
\end{bmatrix}$$

The vectors $\vec{a}$ and $\vec{b}$ are collinear. In fact, $\vec{b}$ can be represented as $2\vec{a}$. Then, a linear combination of $\vec{a}$ and $\vec{b}$ does not allow access to the two-dimensional space, and $\vec{b}$ is **not** linearly independent of $\vec{a}$.