# Intro to Numpy

We use Numpy because it's fast and convenient. 

The basis object in numpy is `ndarray`, short for *n*-dimensional array. `ndarray`s must be homogeneous---that is, composed of the same data type.   

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [5]:
a.shape

(3,)

Matrix dimensions are written (r, c): number of rows by number of columns.

In [7]:
b = np.array([[1,2,3],[4,5,6]])

In [8]:
b.shape

(2, 3)

In [9]:
b.dtype

dtype('int32')

In [12]:
# Number of dimensions
b.ndim

2

In [13]:
a.ndim

1

In [20]:
c = range(10000)

In [21]:
%timeit [i**3 for i in c]

1.97 ms ± 34.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [22]:
numpy_c = np.arange(10000)

In [23]:
%timeit numpy_c**3

14.1 µs ± 131 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [29]:
l1 = np.arange(1, 4)
l2 = np.arange(1, 4)
l1*l2

array([1, 4, 9])

`np.arange` is pretty powerful. 

In [34]:
np.arange(2, 12, 3)

array([ 2,  5,  8, 11])

In [36]:
np.zeros((3, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Identity matrix:

In [38]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.full((3,2), 4) # shape then number

array([[4, 4],
       [4, 4],
       [4, 4]])

In [44]:
np.full((5,4), 2.6, dtype=int) # rounds down

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [50]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [51]:
d = np.array([1,2,3])
np.tile(d, (3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [32]:
np.random.random()

0.054810296667183844

In [53]:
np.random.random((3, 2))

array([[0.83199832, 0.63826802],
       [0.03968566, 0.06000804],
       [0.40180661, 0.64505165]])

In [69]:
a = np.linspace(0, 100, 12)
a

array([  0.        ,   9.09090909,  18.18181818,  27.27272727,
        36.36363636,  45.45454545,  54.54545455,  63.63636364,
        72.72727273,  81.81818182,  90.90909091, 100.        ])

In [71]:
a.reshape(4, 3)

array([[  0.        ,   9.09090909,  18.18181818],
       [ 27.27272727,  36.36363636,  45.45454545],
       [ 54.54545455,  63.63636364,  72.72727273],
       [ 81.81818182,  90.90909091, 100.        ]])

In [77]:
a = np.arange(2, 19, 2)

In [78]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [79]:
a[[2, 4, 6]]

array([ 6, 10, 14])

In [80]:
a = a.reshape((3, 3))

In [89]:
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [90]:
a[2, 2]

18

In [97]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [98]:
b = a.copy()

In [101]:
b[0] = 10

In [102]:
b

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [103]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [104]:
np.shares_memory(a, b)

False

In [114]:
a = a.reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [115]:
b = np.array([[12, 13, 14],[15, 16, 17]])

In [116]:
b

array([[12, 13, 14],
       [15, 16, 17]])

In [119]:
np.vstack((a.T,b))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [121]:
c = np.array([[1],[2],[3],[4]])

In [122]:
np.hstack((a.T, c))

array([[ 0,  4,  8,  1],
       [ 1,  5,  9,  2],
       [ 2,  6, 10,  3],
       [ 3,  7, 11,  4]])

In [123]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [124]:
np.cos(a)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.83907153,  0.0044257 ]])

In [125]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [126]:
np.sum(a)

66

In [127]:
np.median(a)

5.5

In [128]:
a.std()

3.452052529534663

In [129]:
a = np.arange(1, 10).reshape(3,3)

In [130]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
np.linalg.det(a)

0.0

In [137]:
a = np.array([[1, 5], [5, -1]])

In [138]:
np.linalg.inv(a)

array([[ 0.03846154,  0.19230769],
       [ 0.19230769, -0.03846154]])

In [139]:
np.linalg.eig(a)

EigResult(eigenvalues=array([ 5.09901951, -5.09901951]), eigenvectors=array([[ 0.77334214, -0.63398891],
       [ 0.63398891,  0.77334214]]))

In [140]:
b = a.T

In [141]:
np.dot(a, b)

array([[26,  0],
       [ 0, 26]])

In [144]:
a = np.array([1,1,0], dtype=bool)
b = np.array([0, 1, 1], dtype=bool)

In [143]:
a

array([ True,  True, False])

In [145]:
np.logical_or(a,b)

array([ True,  True,  True])

In [146]:
np.logical_and(a,b)

array([False,  True, False])

In [147]:
np.all(a==a)

True

In [152]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [150]:
a.sum(axis=0) # add down columns

array([4, 6])

In [151]:
a.sum(axis=1) # add across rows

array([3, 7])

In [153]:
a.max()

4

In [155]:
a.argmax() # index of max

3

In [157]:
a = np.arange(1, 10)

In [159]:
a.shape

(9,)

In [164]:
b = a[:,np.newaxis]
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [165]:
b.shape

(9, 1)

In [166]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Intro to Pandas

Used for data analysis.